#databases
db.host: kubevuples
db.port: 3306
db.user: root
db.password: kubevuples1234
db.name: kubevuples

#default
default.mode: debug
default.auto_migrate: false
default.listen: 8099
# 配置 unit数字
default.log_level: 4
default.log_format: json
